spring:
  application:
    name: taskManager

  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanager
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml

  security:
    user:
      password: password

springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha

  api-docs:
    path: /v3/api-docs

jwt:
  secret: 9a4f4c55534f5453494e474c454e4f54454e4f5547485345435245544b455931323334353637383930
  expiration: 86400000

server:
  port: 8080
